# Use an official Node.js runtime as a parent image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install project dependencies
RUN npm install

# Your app binds to port 5173 inside the container
EXPOSE 5173

# Command to run the app in development mode
CMD ["npm", "run", "dev"]
