services:
  # Serviço 1: A sua aplicação React (Frontend)
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      # Mapeia a porta 5173 da sua máquina para a porta 5173 do contentor
      - "5173:5173"
    volumes:
      # Partilha a pasta inteira do projeto com o contentor...
      - .:/app
      # ...mas usa um volume anónimo para o node_modules, para que a
      # pasta do contentor não seja sobreposta pela do seu computador.
      - /app/node_modules
    environment:
      # Garante que o Vite detete as alterações de ficheiros dentro do Docker
      - CHOKIDAR_USEPOLLING=true

  # Serviço 2: A sua API falsa com json-server
  api:
    image: node:20-alpine
    command: npx json-server --watch db.json --host 0.0.0.0 --port 3001
    ports:
      - "3001:3001"
    volumes:
      - ./db.json:/app/db.json
    working_dir: /app


