# define a imagem base do container 
FROM node:20-alpine

# define o diretorio de trabalho padrao dentro do contentor
WORKDIR /app

# copia os ficheiros de dependencias para dentro do contentor
COPY package*.json ./

# executa o comando para instalar as dependencias do projeto
RUN npm install

# informa ao docker que o contentor vai expor a porta 5173
EXPOSE 5173

# define o comando padrao que sera executado quando o container iniciar
CMD ["npm", "run", "dev"]

